//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaysCounter2.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaysCounter2.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        public static string color_select {
            get {
                return ResourceManager.GetString("color_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Selector.
        /// </summary>
        public static string color_title {
            get {
                return ResourceManager.GetString("color_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date:.
        /// </summary>
        public static string editor_date {
            get {
                return ResourceManager.GetString("editor_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string editor_date_day {
            get {
                return ResourceManager.GetString("editor_date_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string editor_date_month {
            get {
                return ResourceManager.GetString("editor_date_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string editor_date_year {
            get {
                return ResourceManager.GetString("editor_date_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string editor_loop {
            get {
                return ResourceManager.GetString("editor_loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string editor_loop_day {
            get {
                return ResourceManager.GetString("editor_loop_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        public static string editor_loop_hour {
            get {
                return ResourceManager.GetString("editor_loop_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        public static string editor_loop_minute {
            get {
                return ResourceManager.GetString("editor_loop_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month(s).
        /// </summary>
        public static string editor_loop_month {
            get {
                return ResourceManager.GetString("editor_loop_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second(s).
        /// </summary>
        public static string editor_loop_second {
            get {
                return ResourceManager.GetString("editor_loop_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop will be activated only after the set time has elapsed..
        /// </summary>
        public static string editor_loop_warn {
            get {
                return ResourceManager.GetString("editor_loop_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year(s).
        /// </summary>
        public static string editor_loop_year {
            get {
                return ResourceManager.GetString("editor_loop_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name:.
        /// </summary>
        public static string editor_name {
            get {
                return ResourceManager.GetString("editor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editor_save {
            get {
                return ResourceManager.GetString("editor_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Time:.
        /// </summary>
        public static string editor_time {
            get {
                return ResourceManager.GetString("editor_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string editor_time_hour {
            get {
                return ResourceManager.GetString("editor_time_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string editor_time_minute {
            get {
                return ResourceManager.GetString("editor_time_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string editor_time_second {
            get {
                return ResourceManager.GetString("editor_time_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string editor_time_timeZone {
            get {
                return ResourceManager.GetString("editor_time_timeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event.
        /// </summary>
        public static string editor_title {
            get {
                return ResourceManager.GetString("editor_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0:.} BC).
        /// </summary>
        public static string editor_year_bc {
            get {
                return ResourceManager.GetString("editor_year_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string settings_color {
            get {
                return ResourceManager.GetString("settings_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distant.
        /// </summary>
        public static string settings_color_distant {
            get {
                return ResourceManager.GetString("settings_color_distant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        public static string settings_color_future {
            get {
                return ResourceManager.GetString("settings_color_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        public static string settings_color_past {
            get {
                return ResourceManager.GetString("settings_color_past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time Format.
        /// </summary>
        public static string settings_dateTimeFormat {
            get {
                return ResourceManager.GetString("settings_dateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings.
        /// </summary>
        public static string settings_dateTimeFormat_helpUrl {
            get {
                return ResourceManager.GetString("settings_dateTimeFormat_helpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string settings_default {
            get {
                return ResourceManager.GetString("settings_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Destination Time.
        /// </summary>
        public static string settings_destination {
            get {
                return ResourceManager.GetString("settings_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string settings_destination_always {
            get {
                return ResourceManager.GetString("settings_destination_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Events Only.
        /// </summary>
        public static string settings_destination_future {
            get {
                return ResourceManager.GetString("settings_destination_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string settings_destination_none {
            get {
                return ResourceManager.GetString("settings_destination_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Font.
        /// </summary>
        public static string settings_font {
            get {
                return ResourceManager.GetString("settings_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Font.
        /// </summary>
        public static string settings_font_default {
            get {
                return ResourceManager.GetString("settings_font_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string settings_save {
            get {
                return ResourceManager.GetString("settings_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cape Verde;
        ///Portugal (Azores) without DST;
        ///Greenland (most) with DST.
        /// </summary>
        public static string timeZone_neg0100 {
            get {
                return ResourceManager.GetString("timeZone_neg0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil (Fernando de Noronha), South Georgia and the South Sandwich Islands;
        ///Greenland (most) without DST;
        ///Saint Pierre and Miquelon with DST.
        /// </summary>
        public static string timeZone_neg0200 {
            get {
                return ResourceManager.GetString("timeZone_neg0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada (Newfoundland, Labrador (southeast)) with DST.
        /// </summary>
        public static string timeZone_neg0230 {
            get {
                return ResourceManager.GetString("timeZone_neg0230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina, Brazil (most), Chile (Aysén, Magallanes), Falkland Islands, French Guiana, Paraguay, Suriname, Uruguay;
        ///Saint Pierre and Miquelon without DST;
        ///Bermuda, Canada (Labrador (most), New Brunswick, Nova Scotia, Prince Edward Island), Chile (most), Greenland (Pituffik Space Base) with DST.
        /// </summary>
        public static string timeZone_neg0300 {
            get {
                return ResourceManager.GetString("timeZone_neg0300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada (Newfoundland, Labrador (southeast)) without DST.
        /// </summary>
        public static string timeZone_neg0330 {
            get {
                return ResourceManager.GetString("timeZone_neg0330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anguilla, Antigua and Barbuda, Aruba, Barbados, Bolivia, Brazil (Amazonas (most), Mato Grosso, Mato Grosso do Sul, Rondônia, Roraima), British Virgin Islands, Canada (Quebec (east)), Caribbean Netherlands, Curaçao, Dominica, Dominican Republic, Grenada, Guadeloupe, Guyana, Martinique, Montserrat, Puerto Rico, Saint Barthélemy, Saint Kitts and Nevis, Saint Lucia, Saint Martin, Saint Vincent and the Grenadines, Sint Maarten, Trinidad and Tobago, U.S. Virgin Islands, Venezuela;
        ///Bermuda, Canada (Labrador (most [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZone_neg0400 {
            get {
                return ResourceManager.GetString("timeZone_neg0400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil (Acre, Amazonas (southwest)), Canada (Atikokan, Mishkeegogamang, Southampton Island), Cayman Islands, Colombia, Ecuador (most), Jamaica, Mexico (Quintana Roo), Navassa Island, Panama, Peru;
        ///Bahamas, Canada (Nunavut (east), Ontario (most), Quebec (most)), Cuba, Haiti, Turks and Caicos Islands, United States (Connecticut, Delaware, District of Columbia, Florida (most), Georgia, Indiana (most), Kentucky (east), Maine, Maryland, Massachusetts, Michigan (most), New Hampshire, New Jersey, New York, North  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZone_neg0500 {
            get {
                return ResourceManager.GetString("timeZone_neg0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize, Canada (Saskatchewan (most)), Costa Rica, Ecuador (Galápagos), El Salvador, Guatemala, Honduras, Mexico (most), Nicaragua;
        ///Canada (Manitoba, Nunavut (central), Ontario (west)), Chile (Easter Island), Mexico (northeast border), United States (Alabama, Arkansas, Florida (northwest), Illinois, Indiana (northwest, southwest), Iowa, Kansas (most), Kentucky (west), Louisiana, Michigan (northwest border), Minnesota, Mississippi, Missouri, Nebraska (most), North Dakota (most), Oklahoma, South Dakota (most) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZone_neg0600 {
            get {
                return ResourceManager.GetString("timeZone_neg0600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada (British Columbia (northeast), Yukon), Mexico (Baja California Sur, Nayarit (most), Sinaloa, Sonora), United States (Arizona (most));
        ///Canada (Alberta, British Columbia (southeast), Northwest Territories, Nunavut (west), Saskatchewan (Lloydminster area)), Mexico (Chihuahua (northwest border)), United States (Arizona (Navajo Nation), Colorado, Idaho (most), Kansas (west), Montana, Nebraska (west), New Mexico, Nevada (northeast border), North Dakota (southwest), Oregon (east), South Dakota (west), Texa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZone_neg0700 {
            get {
                return ResourceManager.GetString("timeZone_neg0700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipperton Island, Pitcairn Islands;
        ///Canada (British Columbia (most)), Mexico (Baja California), United States (California, Idaho (north), Nevada (most), Oregon (most), Washington) without DST;
        ///United States (Alaska (most)) with DST.
        /// </summary>
        public static string timeZone_neg0800 {
            get {
                return ResourceManager.GetString("timeZone_neg0800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Polynesia (Gambier Islands);
        ///United States (Alaska (most)) without DST;
        ///United States (Andreanof Islands, Islands of Four Mountains, Near Islands, Rat Islands) with DST.
        /// </summary>
        public static string timeZone_neg0900 {
            get {
                return ResourceManager.GetString("timeZone_neg0900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Polynesia (Marquesas Islands).
        /// </summary>
        public static string timeZone_neg0930 {
            get {
                return ResourceManager.GetString("timeZone_neg0930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Islands, French Polynesia (most), Johnston Atoll, United States (Hawaii);
        ///United States (Andreanof Islands, Islands of Four Mountains, Near Islands, Rat Islands) without DST.
        /// </summary>
        public static string timeZone_neg1000 {
            get {
                return ResourceManager.GetString("timeZone_neg1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Samoa, Jarvis Island, Kingman Reef, Midway Atoll, Niue, Palmyra Atoll.
        /// </summary>
        public static string timeZone_neg1100 {
            get {
                return ResourceManager.GetString("timeZone_neg1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere on Earth (AoE);
        ///Baker Island, Howland Island.
        /// </summary>
        public static string timeZone_neg1200 {
            get {
                return ResourceManager.GetString("timeZone_neg1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso, Gambia, Ghana, Greenland (National Park (east coast)), Guinea, Guinea-Bissau, Iceland, Ivory Coast, Liberia, Mali, Mauritania, Saint Helena, Ascension and Tristan da Cunha, Senegal, Sierra Leone, São Tomé and Príncipe, Togo;
        ///Faroe Islands, Guernsey, Ireland, Isle of Man, Jersey, Portugal (most), Spain (Canary Islands), United Kingdom without DST;
        ///Portugal (Azores) with DST.
        /// </summary>
        public static string timeZone_pos0000 {
            get {
                return ResourceManager.GetString("timeZone_pos0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindom of Elleore without DST.
        /// </summary>
        public static string timeZone_pos0048 {
            get {
                return ResourceManager.GetString("timeZone_pos0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria, Angola, Benin, Cameroon, Central African Republic, Chad, Congo, DR Congo (Équateur, Kinshasa, Kongo Central, Kwango, Kwilu, Mai-Ndombe, Mongala, Nord-Ubangi, Sud-Ubangi, Tshuapa), Equatorial Guinea, Gabon, Morocco, Niger, Nigeria, Tunisia;
        ///Albania, Andorra, Austria, Belgium, Bosnia and Herzegovina, Croatia, Czech Republic, Denmark, France (metropolitan), Germany, Gibraltar, Hungary, Italy, Liechtenstein, Luxembourg, Malta, Monaco, Montenegro, Netherlands (European), North Macedonia, Norway, Poland [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZone_pos0100 {
            get {
                return ResourceManager.GetString("timeZone_pos0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindom of Elleore with DST.
        /// </summary>
        public static string timeZone_pos0148 {
            get {
                return ResourceManager.GetString("timeZone_pos0148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana, Burundi, DR Congo (most), Eswatini, Lesotho, Libya, Malawi, Mozambique, Namibia, Russia (Kaliningrad), Rwanda, South Africa (most), South Sudan, Sudan, Zambia, Zimbabwe;
        ///Akrotiri and Dhekelia, Bulgaria, Cyprus, Egypt, Estonia, Finland, Greece, Israel, Latvia, Lebanon, Lithuania, Moldova, Palestine, Romania, Ukraine (most) without DST;
        ///Albania, Andorra, Austria, Belgium, Bosnia and Herzegovina, Croatia, Czech Republic, Denmark, France (metropolitan), Germany, Gibraltar, Hungary, Italy, Liechtenst [rest of string was truncated]&quot;;.
        /// </summary>
        public static string timeZone_pos0200 {
            get {
                return ResourceManager.GetString("timeZone_pos0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain, Belarus, Comoros, Djibouti, Eritrea, Ethiopia, French Southern and Antarctic Lands (Scattered Islands), Iraq, Jordan, Kenya, Kuwait, Madagascar, Mayotte, Qatar, Russia (most of European part), Saudi Arabia, Somalia, South Africa (Prince Edward Islands), Syria, Tanzania, Türkiye, Uganda, Ukraine (occupied territories), Yemen;
        ///Akrotiri and Dhekelia, Bulgaria, Cyprus, Egypt, Estonia, Finland, Greece, Israel, Latvia, Lebanon, Lithuania, Moldova, Palestine, Romania, Ukraine (most) with DST.
        /// </summary>
        public static string timeZone_pos0300 {
            get {
                return ResourceManager.GetString("timeZone_pos0300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        public static string timeZone_pos0330 {
            get {
                return ResourceManager.GetString("timeZone_pos0330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia, Azerbaijan, French Southern and Antarctic Lands (Crozet Islands), Georgia, Mauritius, Oman, Russia (Astrakhan, Samara, Saratov, Udmurtia, Ulyanovsk), Réunion, Seychelles, United Arab Emirates.
        /// </summary>
        public static string timeZone_pos0400 {
            get {
                return ResourceManager.GetString("timeZone_pos0400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string timeZone_pos0430 {
            get {
                return ResourceManager.GetString("timeZone_pos0430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Southern and Antarctic Lands (Kerguelen Islands, Saint Paul Island, Amsterdam Island), Heard Island and McDonald Islands, Kazakhstan, Maldives, Pakistan, Russia (Bashkortostan, Chelyabinsk, Khanty-Mansi, Kurgan, Orenburg, Perm, Sverdlovsk, Tyumen, Yamalia), Tajikistan, Turkmenistan, Uzbekistan.
        /// </summary>
        public static string timeZone_pos0500 {
            get {
                return ResourceManager.GetString("timeZone_pos0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India, Sri Lanka.
        /// </summary>
        public static string timeZone_pos0530 {
            get {
                return ResourceManager.GetString("timeZone_pos0530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        public static string timeZone_pos0545 {
            get {
                return ResourceManager.GetString("timeZone_pos0545", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh, Bhutan, British Indian Ocean Territory, Kyrgyzstan, Russia (Omsk).
        /// </summary>
        public static string timeZone_pos0600 {
            get {
                return ResourceManager.GetString("timeZone_pos0600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocos Islands, Myanmar.
        /// </summary>
        public static string timeZone_pos0630 {
            get {
                return ResourceManager.GetString("timeZone_pos0630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia, Christmas Island, Indonesia (Sumatra, Java, West Kalimantan, Central Kalimantan), Laos, Mongolia (Bayan-Ölgii, Khovd, Uvs), Russia (Altai Krai, Altai Republic, Kemerovo, Khakassia, Krasnoyarsk, Novosibirsk, Tomsk, Tuva), Thailand, Vietnam.
        /// </summary>
        public static string timeZone_pos0700 {
            get {
                return ResourceManager.GetString("timeZone_pos0700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (Western Australia), Brunei, China, Indonesia (South Kalimantan, East Kalimantan, North Kalimantan, Sulawesi, Lesser Sunda Islands), Malaysia, Mongolia (most), Philippines, Russia (Buryatia, Irkutsk), Singapore.
        /// </summary>
        public static string timeZone_pos0800 {
            get {
                return ResourceManager.GetString("timeZone_pos0800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (Eucla).
        /// </summary>
        public static string timeZone_pos0845 {
            get {
                return ResourceManager.GetString("timeZone_pos0845", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia (Maluku Islands, Western New Guinea), Japan, North Korea, Palau, Russia (Amur, Sakha (most), Zabaykalsky), South Korea, Timor-Leste.
        /// </summary>
        public static string timeZone_pos0900 {
            get {
                return ResourceManager.GetString("timeZone_pos0900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (Northern Territory);
        ///Australia (South Australia, Yancowinna County) without DST.
        /// </summary>
        public static string timeZone_pos0930 {
            get {
                return ResourceManager.GetString("timeZone_pos0930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (Queensland), Guam, Micronesia (Chuuk, Yap), Northern Mariana Islands, Papua New Guinea (most), Russia (Jewish, Khabarovsk, Primorsky, Sakha (central-east));
        ///Australia (Australian Capital Territory, Jervis Bay Territory, New South Wales (most), Tasmania, Victoria) without DST.
        /// </summary>
        public static string timeZone_pos1000 {
            get {
                return ResourceManager.GetString("timeZone_pos1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (Lord Howe Island) without DST;
        ///Australia (South Australia, Yancowinna County) with DST.
        /// </summary>
        public static string timeZone_pos1030 {
            get {
                return ResourceManager.GetString("timeZone_pos1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesia (Kosrae, Pohnpei), New Caledonia, Papua New Guinea (Bougainville), Russia (Magadan, Sakha (east), Sakhalin), Solomon Islands, Vanuatu;
        ///Norfolk Island without DST;
        ///Australia (Australian Capital Territory, Jervis Bay Territory, Lord Howe Island, New South Wales (most), Tasmania, Victoria) with DST.
        /// </summary>
        public static string timeZone_pos1100 {
            get {
                return ResourceManager.GetString("timeZone_pos1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji, Kiribati (Gilbert Islands), Marshall Islands, Nauru, Russia (Chukotka, Kamchatka), Tuvalu, Wake Island, Wallis and Futuna;
        ///New Zealand (most) without DST;
        ///Norfolk Island with DST.
        /// </summary>
        public static string timeZone_pos1200 {
            get {
                return ResourceManager.GetString("timeZone_pos1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand (Chatham Islands) without DST.
        /// </summary>
        public static string timeZone_pos1245 {
            get {
                return ResourceManager.GetString("timeZone_pos1245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati (Phoenix Islands), Samoa, Tokelau, Tonga;
        ///New Zealand (most) with DST.
        /// </summary>
        public static string timeZone_pos1300 {
            get {
                return ResourceManager.GetString("timeZone_pos1300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand (Chatham Islands) with DST.
        /// </summary>
        public static string timeZone_pos1345 {
            get {
                return ResourceManager.GetString("timeZone_pos1345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati (Line Islands).
        /// </summary>
        public static string timeZone_pos1400 {
            get {
                return ResourceManager.GetString("timeZone_pos1400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time: .
        /// </summary>
        public static string ui_currentTime {
            get {
                return ResourceManager.GetString("ui_currentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ui_delete {
            get {
                return ResourceManager.GetString("ui_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this event?
        ///The operation is irrevocable!.
        /// </summary>
        public static string ui_delete_warn {
            get {
                return ResourceManager.GetString("ui_delete_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete these {0} events?
        ///The operation is irrevocable!.
        /// </summary>
        public static string ui_delete_warn_multi {
            get {
                return ResourceManager.GetString("ui_delete_warn_multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ui_delete_warn_title {
            get {
                return ResourceManager.GetString("ui_delete_warn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ui_edit {
            get {
                return ResourceManager.GetString("ui_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ui_new {
            get {
                return ResourceManager.GetString("ui_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Display Range.
        /// </summary>
        public static string ui_outOfRange {
            get {
                return ResourceManager.GetString("ui_outOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string ui_search {
            get {
                return ResourceManager.GetString("ui_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ui_settings {
            get {
                return ResourceManager.GetString("ui_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font modification will take effect after the program is restarted..
        /// </summary>
        public static string ui_settings_font {
            get {
                return ResourceManager.GetString("ui_settings_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Modified.
        /// </summary>
        public static string ui_settings_font_title {
            get {
                return ResourceManager.GetString("ui_settings_font_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language modification will take effect after the program is restarted..
        /// </summary>
        public static string ui_settings_language {
            get {
                return ResourceManager.GetString("ui_settings_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Modified.
        /// </summary>
        public static string ui_settings_language_title {
            get {
                return ResourceManager.GetString("ui_settings_language_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d {1}h {2}m {3}s ago.
        /// </summary>
        public static string ui_timerAgo {
            get {
                return ResourceManager.GetString("ui_timerAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d {1}h {2}m {3}s later.
        /// </summary>
        public static string ui_timerLater {
            get {
                return ResourceManager.GetString("ui_timerLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ui_version {
            get {
                return ResourceManager.GetString("ui_version", resourceCulture);
            }
        }
    }
}
